"""Prototype of a physically explicit growing-filament model.

This package is intentionally independent from the legacy implementations in
``growing_natural_length_model/`` and ``triangular_lattice/``.
"""

from .geometry import (
    ContactDiagnosticType,
    NormalStatus,
    SegmentContact,
    SegmentContactGeometry,
    SegmentDistance,
    SegmentFeature,
    SweptIntersection,
    centerline_intersection,
    closest_nonlocal_segment_contact,
    closest_nonlocal_segment_pair,
    finite_radius_segment_contacts,
    find_swept_nonlocal_intersection,
    geometry_diagnostics,
    has_nonlocal_intersection,
    has_swept_nonlocal_intersection,
    initial_geometry_diagnostic,
    minimum_nonlocal_segment_distance,
    nonlocal_segment_contact_geometry,
    nonlocal_segment_contacts,
    nonlocal_segment_distances,
    segment_closest_points,
    segment_contact,
    segment_contact_geometry,
    segment_segment_contact_geometry,
    segments_intersect,
)
from .model import (
    FilamentState,
    ModelParameters,
    OverdampedGrowingFilament,
    remesh,
)
from .reproducibility import (
    build_manifest,
    canonical_input_hash,
    canonical_state_hash,
    compare_reproducibility,
    load_manifest,
    save_manifest,
)

__all__ = [
    "FilamentState",
    "ModelParameters",
    "OverdampedGrowingFilament",
    "remesh",
    "ContactDiagnosticType",
    "NormalStatus",
    "SegmentContact",
    "SegmentContactGeometry",
    "SegmentDistance",
    "SegmentFeature",
    "SweptIntersection",
    "centerline_intersection",
    "closest_nonlocal_segment_contact",
    "closest_nonlocal_segment_pair",
    "finite_radius_segment_contacts",
    "find_swept_nonlocal_intersection",
    "geometry_diagnostics",
    "has_nonlocal_intersection",
    "has_swept_nonlocal_intersection",
    "initial_geometry_diagnostic",
    "minimum_nonlocal_segment_distance",
    "nonlocal_segment_contact_geometry",
    "nonlocal_segment_contacts",
    "nonlocal_segment_distances",
    "segment_closest_points",
    "segment_contact",
    "segment_contact_geometry",
    "segment_segment_contact_geometry",
    "segments_intersect",
    "build_manifest",
    "canonical_input_hash",
    "canonical_state_hash",
    "compare_reproducibility",
    "load_manifest",
    "save_manifest",
]
